% settings_for_read_paparazzi.m
% script to 



% "ignore" settings
ignl={};                                                                                            % lines in data file that can be ignored 
% ignl={'ALIVE','PONG'};                                                                            % lines in data file that can be ignored 
ignv={};                                                                                            % specific variables columns that can be ignored
%ignv={'LINK_REPORT_ac_id','AUTOPILOT_VERSION_version'};

% custom unit conversion settings
cunit_in =   {'cm', 'mm',      'rad', 'cm/s', 'mm/s',    'rad/s',  'Pa', 'cms', 'centideg', 'decideg', 'degs', 'ms', 'decivolt'};
cunit_out =  { 'm',  'm',      'deg',  'm/s',  'm/s',    'deg/s', 'hPa', 'm/s',      'deg',     'deg','deg/s', 'm/s',       'V'};
cunit_coef = [1e-2, 1e-3, rad2deg(1),   1e-2,   1e-3, rad2deg(1),  1e-2,  1e-2,       1e-2,      1e-1,      1,     1,      1e-1];   % multiplication factors

% custom name conversion settings to enable compatibility with old SUMO scripts
cname_in =  {'ATTITUDE',...                                     % it's possible to use regular expressions
    'IMU_ACCEL_a','t_IMU_ACCEL',...
    't_IMU_GYRO','IMU_GYRO_g',...
    'GPS_mode','GPS_utm_east','GPS_utm_north','GPS_course','GPS_speed',....
    'GPS_climb','GPS_itow','GPS_utm_zone','GPS_nb_err',...
    't_ACTUATORS','ACTUATORS_azimuth','ACTUATORS_elevation','ACTUATORS_tilt',...
    'ACTUATORS_counter','ACTUATORS_can_errs','ACTUATORS_spi_errs',...
    'ACTUATORS_thrust_out','ACTUATORS_pitch_out',...
    't_NAVIGATION_REF','NAVIGATION_REF_utm_east','NAVIGATION_REF_utm_north','NAVIGATION_REF_utm_zone',...
    't_NAVIGATION','NAVIGATION_cur_block','NAVIGATION_cur_stage','NAVIGATION_pos_x',...
    'NAVIGATION_pos_y','NAVIGATION_dist2_wp','NAVIGATION_dist2_home',...
    'NAVIGATION_circle_count','NAVIGATION_oval_count',...
    't_CIRCLE','CIRCLE_center_east','CIRCLE_center_north','CIRCLE_radius',...
    't_SEGMENT','SEGMENT_segment_east_1','SEGMENT_segment_north_1',...
    'SEGMENT_segment_east_2','SEGMENT_segment_north_2',...
    't_DESIRED','DESIRED_roll','DESIRED_pitch','DESIRED_course','DESIRED_x','DESIRED_y',...
    'DESIRED_altitude','DESIRED_climb','DESIRED_airspeed'...
    't_TMP_STATUS','TMP_STATUS_itemp','TMP_STATUS_temp',...
    't_SHT_STATUS','SHT_STATUS_itemp','SHT_STATUS_ihumid','SHT_STATUS_temp','SHT_STATUS_humid',...
    't_TEMP_FINE_WIRE','TEMP_FINE_WIRE_fast_temp','TEMP_FINE_WIRE_packet_count','TEMP_FINE_WIRE_fast_temp_raw',...
    't_FLOW_AP_OTF','FLOW_AP_OTF_velocity','FLOW_AP_OTF_a_attack','FLOW_AP_OTF_a_sidesl',...
    'FLOW_AP_OTF_altitude','FLOW_AP_OTF_checksum','FLOW_AP_OTF_counter',...
    't_WEATHER_METER','WEATHER_METER_pamb','WEATHER_METER_tamb','WEATHER_METER_windspeed',...
    'WEATHER_METER_wind_from','WEATHER_METER_humidity',...
    't_BARO_MS5611','BARO_MS5611_d1','BARO_MS5611_d2','BARO_MS5611_pressure','BARO_MS5611_temp',...
    't_MLX_STATUS','MLX_STATUS_itemp_case','MLX_STATUS_temp_case','MLX_STATUS_itemp_obj','MLX_STATUS_temp_obj'...
    't_AIRSPEED_ETS','AIRSPEED_ETS_adc','AIRSPEED_ETS_offset','AIRSPEED_ETS_scaled'};%,...
%     'AIR_DATA'};                                                                                    % bebop
cname_out = {'ATT',...
    'ACC_','t_ACC',...
    't_GYR','GYR_',...
    'GPS_mod','GPS_utmE','GPS_utmN','GPS_chi','GPS_GS',...
    'GPS_CS','GPS_tow','GPS_utmz','GPS_nberr',...
    't_ACT','ACT_azim','ACT_elev','ACT_a','ACT_b','ACT_c','ACT_d','ACT_e','ACT_f',...
    't_REF','REF_utmE','REF_utmN','REF_utmz',...
    't_NAV','NAV_curblock','NAV_curstage',...
    'NAV_x','NAV_y','NAV_d2wp','NAV_d2ho',...
    'NAV_circc','NAV_ovalc',...
    't_CIR','CIR_E','CIR_N','CIR_r',...
    't_SEG','SEG_E1','SEG_N1','SEG_E2','SEG_N2',...
    't_DES','DES_phi','DES_theta','DES_course','DES_x','DES_y',...
    'DES_alt','DES_CS','DES_AS',...
    't_TMP','TMP_iT','TMP_T',...
    't_SHT','SHT_iT','SHT_iRH','SHT_T','SHT_RH',...
    't_TFI','TFI_T','TFI_count','TFI_R',...
    't_FHP','FHP_asm','FHP_aga','FHP_ags','FHP_alt','FHP_check','FHP_count',...
    't_WWW','WWW_p','WWW_T','WWW_WS','WWW_WD','WWW_RH',...
    't_BAR','BAR_d1','BAR_d2','BAR_P','BAR_T',...
    't_MLX','MLX_iTcase','MLX_Tcase','MLX_iTobj','MLX_Tobj',...
    't_ETS','ETS_adc','ETS_offset','ETS_vel'};%,...
%     'MET'};                                                               